### ISSUE TITLE
Über ad centering needed

### ISSUE THREAD

**Issue by mhulse** [registerguard/drone#31]
Boo!

![screen shot 2014-07-01 at 11 12 07 am](https://cloud.githubusercontent.com/assets/218624/3447255/59dd5a78-014b-11e4-803f-0efd7a7a8074.png)

Here's what I'm doing via our [ad styles](http://advertising.registerguard.com/static/ad_manager/benjamins/css/ad_manager.css) on the main site:

``` css
.advert {
    text-align: center; /* Oldschool centering technique. */
    position: relative; /* Just in case ad decides to `position: absolute;` without a `position: relative;` parent. */
    margin: 0 auto; /* Putting `auto` here to assist `.advert`s that have a width. */
}
    .advert * {
        /* http://meyerweb.com/eric/tools/css/reset/ */
        font-size: 100%;
        font: inherit;
        border: 0;
        margin: 0 auto; /* Centers. */
        padding: 0;
        outline: 0;
    }
    .advert img {
        /* Responsive images: */
        width: auto;
        height: auto;
        max-width: 100%;
        max-height: 100%;
        -ms-interpolation-mode: bicubic;
    }
    .advert iframe { display: block; }
```
